version: '3'

services:

  # A MediaMTX instance with a single configured source on path: /example
  # mediamtx:
  #   image: bluenviron/mediamtx
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - MTX_PATHS_AXIS_SOURCE=rtsp://10.10.90.2/axis-media/media.amp?camera=1

  # Grabbing each frame of the rtsp stream and push to Zenoh using keelson-brefv
  rtsp-to-frames-1:
    image: ghcr.io/mo-rise/keelson:0.1.0-pre.14
    restart: unless-stopped
    network_mode: host
    command:
      [
        "rtsp to_frames -r rise -e seahorse -i sh-1 -s axis-1 --compress jpeg --connect 10.10.0.2 -u rtsp://10.10.90.2/axis-media/media.amp?camera=1"
      ]

  rtsp-to-frames-2:
    image: ghcr.io/mo-rise/keelson:0.1.0-pre.14
    restart: unless-stopped
    network_mode: host
    command:
      [
        "rtsp to_frames -r rise -e seahorse -i sh-1 --compress jpeg -s axis-2 -u rtsp://10.10.90.2/axis-media/media.amp?camera=2"
      ]

  rtsp-to-frames-3:
    image: ghcr.io/mo-rise/keelson:0.1.0-pre.14
    restart: unless-stopped
    network_mode: host
    command:
      [
        "rtsp to_frames -r rise -e seahorse -i sh-1 --compress jpeg -s axis-3 -u rtsp://10.10.90.2/axis-media/media.amp?camera=3"
      ]

  rtsp-to-frames-4:
    image: ghcr.io/mo-rise/keelson:0.1.0-pre.14
    restart: unless-stopped
    network_mode: host
    command:
      [
        "rtsp to_frames -r rise -e seahorse -i sh-1 --compress jpeg -s axis-4 -u rtsp://10.10.90.2/axis-media/media.amp?camera=4"
      ]


