version: '3'
services:

  # navico-radar:
  #   # image: registry.opendlv.org/testing/opendlv-device-radar-navico:v0.0.5
  #   image: registry.opendlv.org/testing/opendlv-device-radar-navico:v0.1.0
  #   restart: unless-stopped
  #   network_mode: "host"
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   # command: "--cid=112 --ip=236.6.7.5 --port=6878 --antenna_height=3 --bearing_alignment=0 --gain=10 --local_interference_rejection=1 --noise_rejection=1 --transmit_lock=0 --rain_clutter=0 --range_alpha=500 --range_bravo=500 --scan_speed=3 --sea_clutter=0 --side_lobe_suppression=0 --target_boost=0 --target_expansion=0 --target_separation=0 --doppler=0"
  #   command: "--cid=112 --ip=236.6.7.5 --port=6878 --antenna_height=3 --bearing_alignment=0 --id=112 --id_bravo=222 --gain=10 --gain_bravo=50 --local_interference_rejection=1 --noise_rejection=1 --transmit_lock=0 --rain_clutter=0 --range_alpha=500 --range_bravo=500 --scan_speed=3 --sea_clutter=0 --side_lobe_suppression=0 --target_boost=0 --target_expansion=0 --target_separation=0 --doppler=0"

  crowsnest-processor-radar:
    image: ghcr.io/mo-rise/crowsnest-processor-opendlv-radar:v0.1.4
    restart: unless-stopped
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - CLUON_CID=112
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - MQTT_BASE_TOPIC=CROWSNEST/SEAHORSE/RADAR/0/SWEEP
      - RADAR_MIN_READING_WEIGHT=0
      - RADAR_SWEEP_ANGULAR_SUBSETTING=4
      - RADAR_SWEEP_RADIAL_SUBSETTING=4

  # crowsnest-processor-radar-two:
  #   image: ghcr.io/mo-rise/crowsnest-processor-opendlv-radar:v0.1.4
  #   restart: unless-stopped
  #   network_mode: "host"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1024M
  #   environment:
  #     - CLUON_CID=222
  #     - MQTT_BROKER_HOST=localhost
  #     - MQTT_BROKER_PORT=1883
  #     - MQTT_BASE_TOPIC=CROWSNEST/SEAHORSE/RADAR/2/SWEEP
  #     - RADAR_MIN_READING_WEIGHT=0
  #     - RADAR_SWEEP_ANGULAR_SUBSETTING=4
  #     - RADAR_SWEEP_RADIAL_SUBSETTING=4