version: '3.9'

services:

  # A MediaMTX instance with a single configured source on path: /example
  mediamtx:
    image: bluenviron/mediamtx
    restart: unless-stopped
    network_mode: host
    environment:
      - MTX_PATHS_AXIS_SOURCE=rtsp://root:RISE2020@10.10.7.61/axis-media/media.amp

  # Grabbing each frame of the rtsp stream and push to Zenoh using keelson-brefv
  rtsp-to-frames:
    image: ghcr.io/mo-rise/keelson:0.1.0-pre.14
    restart: unless-stopped
    network_mode: host
    command:
      [
        "rtsp to_frames -r rise -e seahorse -i sealog-4 -s axis -u rtsp://localhost:8554/axis"
      ]
